// p15/36969/2015
// EVANS WAHOME GICHUKI

#include <stdio.h>
#include <math.h>
#include "RPCops.h" //generated by rpcgen


int *addnum_1_svc(int *num, struct svc_req *client) {//_[version number] appended to name
	static int resl; //Should be static
	FILE *e;


	e = fopen("dev/console", "w"); //Write to console

	if(e == (FILE *)NULL) {
		resl = 0;
		return(&resl);
	}


	fclose(e);

	resl =  num[0] + num[1];

	printf("Client addition request served");


	return(&resl);
}

char **strrev_1_svc(char **str, struct svc_req *client) {

	static char **resl;
	FILE *e;

	e = fopen("dev/console", "w");
	if(e == (FILE *)NULL) {

		resl = 0;
		return(resl);
	}

	char *start = 0, *end = start + strlen(*str) - 1, temp;
	while(end > start) {
		temp = *start;
		*start = *end;
		*end = temp;

		
		start++;
		end--;
	}
	fclose(e);

	
	resl = str;
	printf("Client string reversal request served");

	return(resl);
}

void *sqnum_1_svc(int *num, struct svc_req *client) {

	static int resl;
	FILE *e;

	e = fopen("dev/console", "w");


	if(e == (FILE *)NULL) {


		resl = 0;
		return(&resl);
	}
	fclose(e);

	resl = (*num) * (*num);
	
	printf("Client number squaring request served");
}